version: '3.8'
services:
  workflow-monitor:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=host.docker.internal:9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=password
      - ENVIRONMENT=on-prem
    volumes:
      - ./workflow_metrics.db:/app/workflow_metrics.db
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - default
      
networks:
  default:
    external:
      name: elastic-setup_default
