services:
  workflow-monitor:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=host.docker.internal:9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=password
      - ENVIRONMENT=on-prem
    volumes:
      - ./workflow_metrics.db:/app/workflow_metrics.db
    networks:
      - default
      
networks:
  default:
    driver: bridge
