# Argo Workflows Metrics Collector Configuration

elasticsearch:
  hosts:
  - "localhost:9200" # Update for your Elasticsearch cluster
  # - "elasticsearch.monitoring.svc.cluster.local:9200"  # For in-cluster deployment
  index: "argo-workflow-metrics"
  # Authentication (uncomment if needed)
  # http_auth:
  #   username: "elastic"
  #   password: "changeme"
  # use_ssl: true
  # verify_certs: true

argo:
  namespace: "argo"
  cli_path: "argo" # Path to argo CLI binary

collection:
  interval_seconds: 60 # How often to collect metrics
  max_workflows: 100 # Limit workflows per collection cycle

  # Workflow filters
  include_labels:
  - "monitoring=enabled"
  - "pipeline-type=ml-cv"
  # Only collect workflows newer than this (hours)
  max_age_hours: 24

# Grafana dashboard settings (for reference)
grafana:
  datasource_name: "Elasticsearch-ArgoMetrics"
  dashboard_refresh: "30s"

  # Alert thresholds
  alerts:
    workflow_duration_threshold_seconds: 1800 # 30 minutes
    task_failure_rate_threshold: 0.05 # 5%

# Environment settings
environment:
  cluster_name: "development" # Update for production
  region: "us-west-2"
  team: "ml-cv-team"
